# Site settings
title: ADASE Group
email: adase@skoltech.ru
description: > # this means to ignore newlines until "baseurl:"
  The Advanced Data Analytics in Science and Engineering Group is a research
  organisation focused on the development of novel machine learning methods
  with industrial applications.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://adasegroup.github.io" # the base hostname & protocol for your site
#twitter_username: 
github_username:  adasegroup

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
#job.title: "Assistant Professor"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
